name: label-studio:build

on:
  workflow_run:
    workflows:
      - label-studio:tests
    types:
      - completed 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current commit
      uses: actions/checkout@v2
